//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TestData", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudOffshoreExternal = 
        ///    {
        ///        &quot;id&quot;: &quot;8E0AACA4D71F430DB4557789B22063D0&quot;,
        ///        &quot;name&quot;: &quot;CloudOffshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;7D8CC6A7A0C34D15BC4B073BC8717D0C&quot;,
        ///                &quot;name&quot;: &quot;Report to RMG&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CloudOffshoreExternal {
            get {
                return ResourceManager.GetString("CloudOffshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudOffshoreInternal =
        ///    {
        ///    &quot;id&quot;: &quot;46D41FD202AF4223842504E4B0F54ADA&quot;,
        ///        &quot;name&quot;: &quot;CloudOffshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;ADAC7A9194E74EA9A20BA2A5C779D21D&quot;,
        ///                &quot;name&quot;: &quot;Mandatory Trainings&quot;,
        ///                &quot;description&quot;: &quot;Users are required to complete mandatory training&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CloudOffshoreInternal {
            get {
                return ResourceManager.GetString("CloudOffshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudOnshoreExternal =
        ///    {
        ///        &quot;id&quot;: &quot;1B65B1E2E52D4370B208DEF2C56CBFFB&quot;,
        ///        &quot;name&quot;: &quot;CloudOnshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CloudOnshoreExternal {
            get {
                return ResourceManager.GetString("CloudOnshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudOnshoreInternal = 
        ///    {
        ///            &quot;id&quot;: &quot;308F2B8F8F04400B85A5680AA7503445&quot;,
        ///            &quot;name&quot;: &quot;CloudOnshoreInternal&quot;,
        ///            &quot;tasks&quot;: [
        ///                {
        ///                    &quot;id&quot;: &quot;9AF149D0E99543089C9923DC7B2EC83E&quot;,
        ///                    &quot;name&quot;: &quot;PM Sync-up&quot;,
        ///                    &quot;description&quot;: &quot;User has met with PM to discuss current project&quot;,
        ///                    &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                    &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CloudOnshoreInternal {
            get {
                return ResourceManager.GetString("CloudOnshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCDOffshoreExternal = 
        ///    {
        ///        &quot;id&quot;: &quot;A5C5B74B6C0A4D9E85499F8C047E4204&quot;,
        ///        &quot;name&quot;: &quot;DCDOffshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;7D8CC6A7A0C34D15BC4B073BC8717D0C&quot;,
        ///                &quot;name&quot;: &quot;Report to RMG&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DCDOffshoreExternal {
            get {
                return ResourceManager.GetString("DCDOffshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCDOffshoreInternal = 
        ///    {
        ///        &quot;id&quot;: &quot;C6694C79D1B2458BB53011745BFACAE3&quot;,
        ///        &quot;name&quot;: &quot;DCOffshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;ADAC7A9194E74EA9A20BA2A5C779D21D&quot;,
        ///                &quot;name&quot;: &quot;Mandatory Trainings&quot;,
        ///                &quot;description&quot;: &quot;Users are required to complete mandatory training&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DCDOffshoreInternal {
            get {
                return ResourceManager.GetString("DCDOffshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCDOnshoreExternal = 
        ///    {
        ///        &quot;id&quot;: &quot;D34A46469903400BB8B7D9F831659DA3&quot;,
        ///        &quot;name&quot;: &quot;DCDOnshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DCDOnShoreExternal {
            get {
                return ResourceManager.GetString("DCDOnShoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCDOnshoreInternal=
        ///    {
        ///        &quot;id&quot;: &quot;4C4EBBC86DC244AAB67D3FF3A567AF96&quot;,
        ///        &quot;name&quot;: &quot;DCDOnshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DCDOnshoreInternal {
            get {
                return ResourceManager.GetString("DCDOnshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev9OffshoreExternal = 
        ///    {
        ///        &quot;id&quot;: &quot;05F566967BE14B16BB38DF6545DA04829&quot;,
        ///        &quot;name&quot;: &quot;Dev9OffshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;7D8CC6A7A0C34D15BC4B073BC8717D0C&quot;,
        ///                &quot;name&quot;: &quot;Report to RMG&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dev9OffshoreExternal {
            get {
                return ResourceManager.GetString("Dev9OffshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCDOffshoreInternal = 
        ///    {
        ///        &quot;id&quot;: &quot;DA82E9FBB7F74A70982894D3490FEA9F&quot;,
        ///        &quot;name&quot;: &quot;DCOffshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;ADAC7A9194E74EA9A20BA2A5C779D21D&quot;,
        ///                &quot;name&quot;: &quot;Mandatory Trainings&quot;,
        ///                &quot;description&quot;: &quot;Users are required to complete mandatory training&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dev9OffshoreInternal {
            get {
                return ResourceManager.GetString("Dev9OffshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev9OnshoreExternal = 
        ///    {
        ///        &quot;id&quot;: &quot;E287380A991C4B45B98C5F3A480C5CCC&quot;,
        ///        &quot;name&quot;: &quot;Dev9OnshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dev9OnshoreExternal {
            get {
                return ResourceManager.GetString("Dev9OnshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev9OnshoreInternal = 
        ///    {
        ///        &quot;id&quot;: &quot;55F48035FAED48E9929622BD87120B8B&quot;,
        ///        &quot;name&quot;: &quot;Dev9OnshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dev9OnshoreInternal {
            get {
                return ResourceManager.GetString("Dev9OnshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic2020OffshoreExternal  =
        ///    {
        ///        &quot;id&quot;: &quot;8B134D64CA99439EA94FEF0B7392C916&quot;,
        ///        &quot;name&quot;: &quot;Logic2020OffshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;7D8CC6A7A0C34D15BC4B073BC8717D0C&quot;,
        ///                &quot;name&quot;: &quot;Report to RMG&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logic2020OffshoreExternal {
            get {
                return ResourceManager.GetString("Logic2020OffshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic2020OffshoreInternal = 
        ///    {
        ///        &quot;id&quot;: &quot;734728E8198546F99714DA6E6A080788&quot;,
        ///        &quot;name&quot;: &quot;Logic2020OffshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;ADAC7A9194E74EA9A20BA2A5C779D21D&quot;,
        ///                &quot;name&quot;: &quot;Mandatory Trainings&quot;,
        ///                &quot;description&quot;: &quot;Users are required to complete mandatory training&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logic2020OffshoreInternal {
            get {
                return ResourceManager.GetString("Logic2020OffshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic2020OnshoreExternal =
        ///    {
        ///        &quot;id&quot;: &quot;6F555DEE6CD94A4F990079ECCEEDFC75&quot;,
        ///        &quot;name&quot;: &quot;Logic2020OnshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            },
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logic2020OnshoreExternal {
            get {
                return ResourceManager.GetString("Logic2020OnshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic2020OnshoreInternal = 
        ///    {
        ///        &quot;id&quot;: &quot;E1DA48BC2F1E4D91AF79EF4B9FB6338E&quot;,
        ///        &quot;name&quot;: &quot;Logic2020OnshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///            }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logic2020OnshoreInternal {
            get {
                return ResourceManager.GetString("Logic2020OnshoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePointOffshoreExternal = 
        ///    {
        ///        &quot;id&quot;: &quot;E8365F87D8C64FBF9A6838324C0745B1&quot;,
        ///        &quot;name&quot;: &quot;SharePointOffshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;7D8CC6A7A0C34D15BC4B073BC8717D0C&quot;,
        ///                &quot;name&quot;: &quot;Report to RMG&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SharePointOffshoreExternal {
            get {
                return ResourceManager.GetString("SharePointOffshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePointOffshoreInternal = 
        ///    {
        ///        &quot;id&quot;: &quot;EBA4ED48BB1B4B66900E23EF4A2F35B7&quot;,
        ///        &quot;name&quot;: &quot;SharePointOffshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;ADAC7A9194E74EA9A20BA2A5C779D21D&quot;,
        ///                &quot;name&quot;: &quot;Mandatory Trainings&quot;,
        ///                &quot;description&quot;: &quot;Users are required to complete mandatory training&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SharePointOffShoreInternal {
            get {
                return ResourceManager.GetString("SharePointOffShoreInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePointOnshoreExternal = 
        ///    {
        ///        &quot;id&quot;: &quot;4F9A2B05C519402796909EB3F56BA8AC&quot;,
        ///        &quot;name&quot;: &quot;SharePointOnshoreExternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SharePointOnshoreExternal {
            get {
                return ResourceManager.GetString("SharePointOnshoreExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePointOnshoreInternal = 
        ///    {
        ///        &quot;id&quot;: &quot;5EA61A67985B404AB2A50EEBDFF1BB46&quot;,
        ///        &quot;name&quot;: &quot;SharePointOnshoreInternal&quot;,
        ///        &quot;tasks&quot;: [
        ///            {
        ///                &quot;id&quot;: &quot;2179AEEF508748A7BFCDB1AD51A8FCAA&quot;,
        ///                &quot;name&quot;: &quot;UST ID Setup&quot;,
        ///                &quot;description&quot;: &quot;ID for user has been received and activated&quot;,
        ///                &quot;employeeInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;,
        ///                &quot;managerInstructions&quot;: &quot;a_path_to_an_md_doc.imanendpoint&quot;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SharePointOnshoreInternal {
            get {
                return ResourceManager.GetString("SharePointOnshoreInternal", resourceCulture);
            }
        }
    }
}
